# Generated by Django 2.2 on 2020-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTutorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('start_at', models.CharField(max_length=100)),
                ('end_at', models.CharField(max_length=100)),
                ('edit_by', models.CharField(default='', max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SCHEDULE',
                'verbose_name_plural': 'SCHEDULE',
                'db_table': 'user_tutor_schedule',
            },
        ),
    ]
