# Generated by Django 2.2 on 2020-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertutorschedule',
            name='event_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
