# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_schedule', '0002_usertutorschedule_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertutorschedule',
            options={'verbose_name': 'SCHEDULE', 'verbose_name_plural': ''},
        ),
    ]
