# Generated by Django 2.2 on 2020-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.PositiveIntegerField()),
                ('tutor_name', models.CharField(max_length=100)),
                ('student_id', models.PositiveIntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('order_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('due_begin_time', models.DateTimeField()),
                ('due_end_time', models.DateTimeField()),
                ('webrtc_id', models.CharField(default='', max_length=100)),
                ('real_begin_time', models.DateTimeField(blank=True, null=True)),
                ('real_end_time', models.DateTimeField(blank=True, null=True)),
                ('real_duration', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0)),
                ('tutor_score', models.IntegerField(default=10)),
                ('student_score', models.IntegerField(default=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'db_table': 'activity_entity',
            },
        ),
    ]
