# Generated by Django 2.2 on 2020-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityentity',
            options={'verbose_name': 'activity', 'verbose_name_plural': 'ACTIVITY'},
        ),
    ]
