# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_admin', '0002_auto_20200624_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityentity',
            options={'verbose_name': 'activity', 'verbose_name_plural': ''},
        ),
    ]
