# Generated by Django 2.2 on 2020-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminClassModel',
            new_name='ClassAdminModel',
        ),
    ]
