# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_admin', '0002_auto_20200704_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classadminmodel',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
