# Generated by Django 2.2 on 2020-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_admin', '0002_auto_20200602_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'COURSE'},
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='edit_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
