# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_admin', '0003_auto_20200624_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Course', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='courselevel',
            options={'verbose_name': 'Course Level', 'verbose_name_plural': ''},
        ),
    ]
