# Generated by Django 2.2 on 2020-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=45)),
                ('tutor_id', models.PositiveIntegerField()),
                ('tutor_name', models.CharField(max_length=100)),
                ('student_id', models.PositiveIntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('order_status', models.PositiveIntegerField(default=1)),
                ('total_original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('total_refundable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_status', models.IntegerField(default=0)),
                ('refund_apply_time', models.DateTimeField(blank=True, null=True)),
                ('refunded_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Management',
                'verbose_name_plural': 'Order Management',
                'db_table': 'sale_order',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_level_id', models.PositiveIntegerField()),
                ('course_level_name', models.CharField(max_length=45)),
                ('course_begin_time', models.DateTimeField()),
                ('course_end_time', models.DateTimeField()),
                ('course_tutor_id', models.PositiveIntegerField()),
                ('course_tutor_name', models.CharField(max_length=100)),
                ('course_status', models.PositiveIntegerField(default=1)),
                ('course_income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_refundable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_refund_apply_time', models.DateTimeField(blank=True, null=True)),
                ('course_refunded_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Course',
                'verbose_name_plural': 'Order Courses',
                'db_table': 'sale_order_course',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('order_income_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_income_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('thirdparty_fee_radio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger_type', models.IntegerField(default=1)),
                ('ledger_day', models.IntegerField(default=1)),
                ('self_income_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('partner_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('thirdparty_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ORDER FINANCE',
                'verbose_name_plural': 'ORDER FINANCE',
                'db_table': 'sale_order_finance',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.PositiveIntegerField(default=1)),
                ('payment_method_id', models.PositiveIntegerField()),
                ('payment_method_name', models.CharField(max_length=100)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.PositiveIntegerField(default=1)),
                ('thirdparty_payment_no', models.CharField(max_length=100)),
                ('payment_apply_time', models.DateTimeField()),
                ('payment_success_time', models.DateTimeField(blank=True, null=True)),
                ('payment_failture_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ORDER PAYMENT',
                'verbose_name_plural': 'ORDER PAYMENT',
                'db_table': 'sale_order_payment',
            },
        ),
    ]
