# Generated by Django 2.2 on 2020-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_admin', '0003_auto_20200705_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='order_type',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, '微信'), (2, '支付宝')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额'),
        ),
    ]
