# Generated by Django 2.2 on 2020-07-05 10:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sale_admin', '0004_auto_20200705_1802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='saleordercourse',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='saleordercourse',
            name='course_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleordercourse',
            name='course_student_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleordercourse',
            name='course_student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saleordercourse',
            name='course_status',
            field=models.PositiveIntegerField(choices=[(1, '未授课'), (2, '已授课'), (3, '已退课')], default=1),
        ),
    ]
