# Generated by Django 2.2 on 2020-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20200602_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTutorSchedule',
        ),
    ]
