# Generated by Django 2.2 on 2020-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_delete_usertutorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_phone', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_sex', models.IntegerField()),
                ('user_profile_url', models.CharField(default='', max_length=255)),
                ('user_wx_openid', models.CharField(default='', max_length=100)),
                ('user_wx_unionid', models.CharField(default='', max_length=100)),
                ('has_license', models.BooleanField(default=False)),
                ('user_strong_point', models.CharField(blank=True, default='', max_length=255)),
                ('user_introduce', models.CharField(default='', max_length=255)),
                ('min_student_age', models.IntegerField(default=0)),
                ('max_student_age', models.IntegerField(default=0)),
                ('my_videos_url', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('register_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TUTOR INFO',
                'verbose_name_plural': 'TUTOR INFO',
                'db_table': 'user_tutor_info',
            },
        ),
        migrations.DeleteModel(
            name='UserMemeberInfo',
        ),
    ]
