# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20200704_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorinfo',
            options={'verbose_name': 'TUTOR INFO', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='usertutorresume',
            options={'verbose_name': 'USER RESUME', 'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='tutorinfo',
            name='class_record_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
