# Generated by Django 2.2 on 2020-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20200705_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorinfo',
            name='user_sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=0),
        ),
    ]
