# Generated by Django 2.2 on 2020-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=255)),
                ('textbook_title', models.CharField(max_length=100)),
                ('textbook_url', models.CharField(default='', max_length=255)),
                ('textbook_desc', models.CharField(default='', max_length=255)),
                ('tag', models.CharField(default='', max_length=255)),
                ('edit_by', models.PositiveIntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TEXTBOOK',
                'verbose_name_plural': 'TEXTBOOKS',
                'db_table': 'textbook_content',
            },
        ),
    ]
