# Generated by Django 2.2 on 2020-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookcontent',
            name='textbook_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
