# Generated by Django 2.2 on 2020-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_admin', '0002_auto_20200528_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbookcontent',
            old_name='unit_name',
            new_name='unit_title',
        ),
        migrations.AddField(
            model_name='textbookcontent',
            name='grammar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='textbookcontent',
            name='level_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookcontent',
            name='level_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
