# Generated by Django 2.2 on 2020-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_admin', '0003_auto_20200602_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookcontent',
            name='edit_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
