# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_admin', '0006_auto_20200603_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookcontent',
            options={'verbose_name': 'TEXTBOOK', 'verbose_name_plural': ''},
        ),
    ]
