# Generated by Django 2.2 on 2020-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_phone', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('user_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('user_age', models.IntegerField(verbose_name='年龄')),
                ('user_sex', models.IntegerField(verbose_name='性别')),
                ('user_profile_url', models.CharField(default='', max_length=255, verbose_name='照片')),
                ('user_wx_openid', models.CharField(default='', max_length=100)),
                ('user_wx_unionid', models.CharField(default='', max_length=100)),
                ('total_course', models.IntegerField(default=0, verbose_name='总课程数')),
                ('ing_course', models.IntegerField(default=0, verbose_name='已上')),
                ('done_course', models.IntegerField(default=0, verbose_name='未上')),
                ('register_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'STUDENT INFO',
                'verbose_name_plural': 'STUDENT INFO',
                'db_table': 'user_student_info',
            },
        ),
    ]
