# Generated by Django 2.2 on 2020-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': 'STUDENT INFO', 'verbose_name_plural': ''},
        ),
    ]
